## np.sort

In [3]:
## It returns an sorted copy of an array
import numpy as np
a = np.random.randint(1,100,15)
a

array([58, 64, 16, 13,  3, 78, 51, 40, 73, 57, 98, 96, 32, 83, 79],
      dtype=int32)

In [6]:
np.sort(a)

array([ 3, 13, 16, 32, 40, 51, 57, 58, 64, 73, 78, 79, 83, 96, 98],
      dtype=int32)

In [5]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[10, 64, 97, 44],
       [81, 23, 75, 56],
       [13,  8,  1, 32],
       [92, 94, 47, 31],
       [ 5, 22, 82, 48],
       [ 8, 43, 65, 62]], dtype=int32)

In [8]:
np.sort(b) ## by default it sort our array row wise

array([[10, 44, 64, 97],
       [23, 56, 75, 81],
       [ 1,  8, 13, 32],
       [31, 47, 92, 94],
       [ 5, 22, 48, 82],
       [ 8, 43, 62, 65]], dtype=int32)

In [9]:
## If we want to sort our array column wise so give write axis = 0
np.sort(b, axis = 0)

array([[ 5,  8,  1, 31],
       [ 8, 22, 47, 32],
       [10, 23, 65, 44],
       [13, 43, 75, 48],
       [81, 64, 82, 56],
       [92, 94, 97, 62]], dtype=int32)

In [10]:
## if we want to sort descending wise so we need to write [::-1]
np.sort(b, axis = 0)[::-1]

array([[92, 94, 97, 62],
       [81, 64, 82, 56],
       [13, 43, 75, 48],
       [10, 23, 65, 44],
       [ 8, 22, 47, 32],
       [ 5,  8,  1, 31]], dtype=int32)

In [11]:
## we dont use sorted function because it gives us python list and np.sort gives us array, thats why we will use np.sort

# np.append()
## it appends value along the mentioned axis at the and of the array

In [12]:
a

array([58, 64, 16, 13,  3, 78, 51, 40, 73, 57, 98, 96, 32, 83, 79],
      dtype=int32)

In [13]:
np.append(a,200)

array([ 58,  64,  16,  13,   3,  78,  51,  40,  73,  57,  98,  96,  32,
        83,  79, 200])

In [20]:
b

array([[10, 64, 97, 44],
       [81, 23, 75, 56],
       [13,  8,  1, 32],
       [92, 94, 47, 31],
       [ 5, 22, 82, 48],
       [ 8, 43, 65, 62]], dtype=int32)

In [32]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[10., 64., 97., 44.,  1.],
       [81., 23., 75., 56.,  1.],
       [13.,  8.,  1., 32.,  1.],
       [92., 94., 47., 31.,  1.],
       [ 5., 22., 82., 48.,  1.],
       [ 8., 43., 65., 62.,  1.]])

# np.concatenate()
## This function concatenate a sequence of arrays along an existing axis 

In [33]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [34]:
np.concatenate((c,d),axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
# Rule 1: Arrays ki dimensions same honi chahiye
# Rule 2: axis=0 par columns same honi chahiye
# Rule 3: axis=1 par rows same honi chahiye