## Numpy Practice

In [1]:
import numpy as np
a = np.array([1,2,3]) #It is an 1D array
print(type(a))

<class 'numpy.ndarray'>


In [10]:
b= np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [13]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c.ndim)

3


In [14]:
np.array([1,2,3], dtype = float)

array([1., 2., 3.])

## np.arange

In [4]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## np.ones, np.zeros & np.random

In [10]:
np.ones((3,4)) # It is used to initialize the arrays

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
a = np.ones((2,3,4))

print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.random.random((3,4)) # it give us random number ebtween 0 and 1

array([[0.01542304, 0.73638112, 0.61458517, 0.97190091],
       [0.74321706, 0.82530439, 0.74657984, 0.28113583],
       [0.75927122, 0.37596587, 0.89870324, 0.67359646]])

## np.linspace (linear space)

In [3]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

## np.identity

In [4]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [6]:
a1 = np.arange(10)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
a2 = np.arange(12, dtype = "float").reshape(3,4)
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [8]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
a2.shape # it shows the total no. of rows and column

(3, 4)

In [14]:
a3.size # it shows total number of items in an array.

8

In [17]:
a3.itemsize

8

In [18]:
print(a2.dtype)

float64


## Changing Data Type

In [20]:
a3.dtype

dtype('int64')

In [24]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Scalar Operations

In [28]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
print(np.sum(a1))

66


## Vector operations

In [33]:
## in this operation we apply operation in 2 numpy arrays

In [34]:
print(a1+a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


## Array Functions

In [43]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[84., 52., 42.],
       [53., 76., 69.],
       [66., 35., 92.]])

In [47]:
np.max(a1)

np.float64(92.0)

In [48]:
np.sum(a1)

np.float64(569.0)

In [52]:
print(np.prod(a1))

1.083603202665984e+16


In [56]:
np.prod(a1, axis = 0) # 1 is equal to row and 0 is equal to column

array([293832., 138320., 266616.])

In [60]:
np.mean(a1, axis = 1)

array([59.33333333, 66.        , 64.33333333])

In [61]:
np.median(a1)

np.float64(66.0)

In [62]:
np.std(a1)

np.float64(18.07870311092141)

In [63]:
np.var(a1)

np.float64(326.8395061728395)

## Dot Product

In [65]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a3 = np.arange(12,24).reshape(4,3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [68]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

## log and exponent

In [69]:
a1

array([[84., 52., 42.],
       [53., 76., 69.],
       [66., 35., 92.]])

In [70]:
np.log(a1)

array([[4.4308168 , 3.95124372, 3.73766962],
       [3.97029191, 4.33073334, 4.2341065 ],
       [4.18965474, 3.55534806, 4.52178858]])

In [71]:
np.exp(a1)

array([[3.02507732e+36, 3.83100800e+22, 1.73927494e+18],
       [1.04137594e+23, 1.01480039e+33, 9.25378173e+29],
       [4.60718663e+28, 1.58601345e+15, 9.01762841e+39]])

## Indexing

In [2]:
a1= np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [5]:
a1[-1]

np.int64(9)

In [6]:
a2[1,2]

np.int64(6)

In [7]:
a3[0,1,1]

np.int64(3)

## Slicing

In [8]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a1[2:5]

array([2, 3, 4])

In [15]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
a2[2,:]

array([ 8,  9, 10, 11])

In [27]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [21]:
a2[:,2]

array([ 2,  6, 10])

In [31]:
a2[1::3,::3]

array([[4, 7]])

In [22]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [36]:
a2[0:2:,1::]

array([[1, 2, 3],
       [5, 6, 7]])

In [23]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [39]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [51]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [53]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Iteration on Numpy Array

In [57]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [59]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [60]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [61]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Transpose

In [63]:
np.transpose(a2) ## It converts rows into column and column into rows

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [66]:
a2.T # easy syntax

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## Ravel

In [68]:
## it converts any dimension of array into 1d array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Stacking

In [71]:
## In Horizontal Stacking rows need to be equal to each other
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(15).reshape(3,5)
np.hstack((a4,a5))    

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  4],
       [ 4,  5,  6,  7,  5,  6,  7,  8,  9],
       [ 8,  9, 10, 11, 10, 11, 12, 13, 14]])

In [72]:
## In Vstack columns needs to be equal
a6 = np.arange(12).reshape(4,3)
a7 = np.arange(15).reshape(5,3)
np.vstack((a6,a7))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [1]:
import os
print(os.getcwd())

C:\Users\adity
