## np.sort

In [1]:
## It returns an sorted copy of an array
import numpy as np
a = np.random.randint(1,100,15)
a

array([63, 15,  2, 99, 52, 33, 75, 11, 91,  5, 12, 61, 58, 38, 85],
      dtype=int32)

In [2]:
np.sort(a)

array([ 2,  5, 11, 12, 15, 33, 38, 52, 58, 61, 63, 75, 85, 91, 99],
      dtype=int32)

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[68, 38, 17,  4],
       [66, 27, 89, 73],
       [12, 12, 93, 64],
       [34, 94, 88, 65],
       [55, 80, 43, 65],
       [37, 94, 10, 57]], dtype=int32)

In [4]:
np.sort(b) ## by default it sort our array row wise

array([[ 4, 17, 38, 68],
       [27, 66, 73, 89],
       [12, 12, 64, 93],
       [34, 65, 88, 94],
       [43, 55, 65, 80],
       [10, 37, 57, 94]], dtype=int32)

In [5]:
## If we want to sort our array column wise so give write axis = 0
np.sort(b, axis = 0)

array([[12, 12, 10,  4],
       [34, 27, 17, 57],
       [37, 38, 43, 64],
       [55, 80, 88, 65],
       [66, 94, 89, 65],
       [68, 94, 93, 73]], dtype=int32)

In [6]:
## if we want to sort descending wise so we need to write [::-1]
np.sort(b, axis = 0)[::-1]

array([[68, 94, 93, 73],
       [66, 94, 89, 65],
       [55, 80, 88, 65],
       [37, 38, 43, 64],
       [34, 27, 17, 57],
       [12, 12, 10,  4]], dtype=int32)

In [7]:
## we dont use sorted function because it gives us python list and np.sort gives us array, thats why we will use np.sort

# np.append()
## it appends value along the mentioned axis at the and of the array

In [8]:
a

array([63, 15,  2, 99, 52, 33, 75, 11, 91,  5, 12, 61, 58, 38, 85],
      dtype=int32)

In [9]:
np.append(a,200)

array([ 63,  15,   2,  99,  52,  33,  75,  11,  91,   5,  12,  61,  58,
        38,  85, 200])

In [10]:
b

array([[68, 38, 17,  4],
       [66, 27, 89, 73],
       [12, 12, 93, 64],
       [34, 94, 88, 65],
       [55, 80, 43, 65],
       [37, 94, 10, 57]], dtype=int32)

In [11]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[68., 38., 17.,  4.,  1.],
       [66., 27., 89., 73.,  1.],
       [12., 12., 93., 64.,  1.],
       [34., 94., 88., 65.,  1.],
       [55., 80., 43., 65.,  1.],
       [37., 94., 10., 57.,  1.]])

# np.concatenate()
## This function concatenate a sequence of arrays along an existing axis 

In [12]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c,d),axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
# Rule 1: Arrays ki dimensions same honi chahiye
# Rule 2: axis=0 par columns same honi chahiye
# Rule 3: axis=1 par rows same honi chahiye
## you can use it in replacement of hstack or vstack

# np.unique()
## with the help of this method, we can get the unique values from an array. 

In [17]:
e = np.array([1,2,3,4,5,1,7,2,4,6,8,9,])
np.unique(e, return_index = True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4,  9,  6, 10, 11]))

# np.expand_dims()
## With the help of this method we can get the expanded dimensioins of the array

In [18]:
a = np.random.randint(1,100,15)
a

array([52, 48,  8, 51, 65, 51,  2, 42, 83, 67, 72, 13, 84, 17, 96],
      dtype=int32)

In [19]:
np.expand_dims(a, axis = 0)

array([[52, 48,  8, 51, 65, 51,  2, 42, 83, 67, 72, 13, 84, 17, 96]],
      dtype=int32)

In [20]:
np.expand_dims(a, axis = 1)

array([[52],
       [48],
       [ 8],
       [51],
       [65],
       [51],
       [ 2],
       [42],
       [83],
       [67],
       [72],
       [13],
       [84],
       [17],
       [96]], dtype=int32)

# np.where()
## This function returns the indices of elements in an input array where the given condition is satisfied.

In [21]:
a

array([52, 48,  8, 51, 65, 51,  2, 42, 83, 67, 72, 13, 84, 17, 96],
      dtype=int32)

In [23]:
np.where(a>50,"Pass","Fail")

array(['Pass', 'Fail', 'Fail', 'Pass', 'Pass', 'Pass', 'Fail', 'Fail',
       'Pass', 'Pass', 'Pass', 'Fail', 'Pass', 'Fail', 'Pass'],
      dtype='<U4')

In [26]:
np.where(a>50) ## It gives indices of the element which satisfied the conditions and in boolean indexing it gives us the value not the indices

(array([ 0,  3,  4,  5,  8,  9, 10, 12, 14]),)

In [27]:
## replace all values >50 with 0
np.where(a>50, 0,a)

array([ 0, 48,  8,  0,  0,  0,  2, 42,  0,  0,  0, 13,  0, 17,  0],
      dtype=int32)

In [28]:
np.where(a%2==0, 0,a)

array([ 0,  0,  0, 51, 65, 51,  0,  0, 83, 67,  0, 13,  0, 17,  0],
      dtype=int32)

# np.argmax() & np.argmin()
## it returns the indices of the max and min elements of the array in a particular axis

In [30]:
marks = np.array([85, 92, 78, 95, 88])
top_student = np.argmax(marks)
print(top_student)
## It returns the indice of the maximum element

3


In [31]:
a = np.random.randint(1,15,12).reshape(3,4)
a

array([[ 7,  4,  4,  8],
       [10, 13, 14,  6],
       [ 3,  7,  4, 12]], dtype=int32)

In [33]:
np.argmax(a, axis= 1)

array([3, 2, 3])

In [34]:
np.argmin(a, axis=0)

array([2, 0, 0, 1])

# np.cumsum()
## This function is used when we want to compute the cumulative sum of an array elements over a given axis

In [35]:
np.cumsum(a, axis = 1)

array([[ 7, 11, 15, 23],
       [10, 23, 37, 43],
       [ 3, 10, 14, 26]])

In [38]:
np.cumsum(a, axis = 0) ## If we didn't mention axis so it convert it into 1D array and then show cumulative sum

array([[ 7,  4,  4,  8],
       [17, 17, 18, 14],
       [20, 24, 22, 26]])

In [39]:
np.cumprod(a, axis = 1)

array([[    7,    28,   112,   896],
       [   10,   130,  1820, 10920],
       [    3,    21,    84,  1008]])

# np.percentile
## This function used to compute the nth percentile of the given data(array elements) along the specified axis.

In [41]:
np.percentile(a, [25,50,75]) ## multiple percentiles in one go.

array([ 4. ,  7. , 10.5])

In [42]:
np.percentile(a,50,axis =  0)

array([7., 7., 4., 8.])

# np.histogram
## Numpy has a built in function which represents the frequency of data distribution in the graphical form

In [2]:
import numpy as np
a = np.array([11,53,28,50,38,3794,92,5,30,68,9,78,2,21])
np.histogram(a, bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([3, 1, 2, 2, 0, 2, 1, 1, 0, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [3]:
## It doesn't draw graph but it give us frequency count

# np.corrcoef()
## Return Pearson product-moment correlation coefficient

In [4]:
# Correlation Range
# +1  -> Perfect Positive Correlation
# +0.8 -> Strong Positive Correlation
# +0.5 -> Moderate Positive Correlation
#  0  -> No Correlation
# -0.5 -> Moderate Negative Correlation
# -0.8 -> Strong Negative Correlation
# -1  -> Perfect Negative Correlation

In [8]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)[0,1]

np.float64(0.25344572266626864)

# np.isin()
## With the help of this method we can see that one array having values are checked in a different numpy array having different elements with different sizes

In [12]:
a = np.array([10,20,30,40,50,20])
np.isin(a,[20,50])

array([False,  True, False, False,  True,  True])

In [13]:
a[np.isin(a,[20,50])]

array([20, 50, 20])

In [14]:
a = np.array([11,53,28,50,38,3794,92,5,30,68,9,78,2,21])
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([50, 30])

# np.put()
## np.put() is used to replace or insert values at specific indices of an array.

In [17]:
np.put(a, 1,15)

In [18]:
a

array([  11,   15,   28,   50,   38, 3794,   92,    5,   30,   68,    9,
         78,    2,   21])

In [19]:
np.put(a,[0,1],[110,510])

In [21]:
a ## It changes permanentaly

array([ 110,  510,   28,   50,   38, 3794,   92,    5,   30,   68,    9,
         78,    2,   21])